# Filter

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r'C:\Users\DeLL\Desktop\ML\fullcourse\DR\Data\Swarm Behavior Data\aligned_reduced.csv')

In [3]:
df.head()

Unnamed: 0       x1      y1  xVel1  yVel1  xA1  yA1     xS1     yS1  xC1  \
0           0 -1414.14 -535.22 -17.88  -7.23  0.0  0.0    0.00    0.00  0.0   
1           4 -1406.36  698.39 -16.54  -6.95 -1.0  0.0 -944.07 -396.62  0.0   
2           8 -1404.81  939.49  -5.44  -2.20  0.0  0.0    0.00    0.00  0.0   
3          12 -1403.15 -350.53  -6.39   0.13  0.0  0.0    0.00    0.00  0.0   
4          16 -1402.23  259.25  -6.22  14.16 -1.0  0.0  -20.01   60.79  0.0   

   ...  yVel200  xA200  yA200  xS200  yS200  xC200  yC200  nAC200  nS200  \
0  ...   -16.85   0.00   0.00    0.0   0.00   0.00   0.00      29      0   
1  ...   -12.61   0.00  -1.00    0.0   0.00   0.00   0.00      13      0   
2  ...   -10.69   0.00   0.00    0.0   0.00   0.00   0.00      27      1   
3  ...     0.63  -0.56   0.06    0.0   0.00   0.16  -0.28      30      0   
4  ...    -9.77  -1.00   1.00    4.0  -0.04   0.00   0.00      18      3   

   Class  
0      0  
1      0  
2      0  
3      1  
4      0  

[5 rows x 2402 columns]

In [4]:
df.shape

(6004, 2402)

In [5]:
y = np.asarray(df.Class)
X = np.asarray(df.drop('Class',axis=1))

In [6]:
X.shape

(6004, 2401)

In [7]:
y.shape

(6004,)

In [8]:
np.unique(y)

array([0, 1], dtype=int64)

In [9]:
(y==0).sum()

4115

In [10]:
(y==1).sum()

1889

In [11]:
from sklearn.feature_selection import SelectKBest

In [12]:
SelectKBest?

In [13]:
#k = 500
F = SelectKBest(k=500)

In [14]:
F

SelectKBest(k=500, score_func=<function f_classif at 0x000001BA87575DC8>)

In [15]:
T = F.fit(X,y)

In [17]:
len(T.scores_)

2401

In [18]:
T.scores_

array([ 59.07025412,  47.70372461,  10.82132435, ..., 270.73448244,
       536.5090956 ,  85.83897516])

In [25]:
idx = np.argsort(T.scores_)[::-1]

In [26]:
A = np.asarray(df.columns)
A[idx]

array(['yVel41', 'yVel95', 'yVel56', ..., 'xS2', 'yS31', 'yS105'],
      dtype=object)

In [27]:
X_new = T.transform(X)

In [28]:
X_new.shape

(6004, 500)

# Wrapper 

In [29]:
from sklearn.linear_model import LogisticRegression
#from sklearn.svm import LinearSVC
from sklearn.feature_selection import RFE
#from sklearn.feature_selection import RFECV

In [30]:
M = LogisticRegression()
# M = LinearSVC()

In [31]:
S = RFE(M,200)
#S = RFECV(M,cv=5)

In [34]:
#T = S.fit(X,y)
#T = S.fit(X_new,y)
import pickle
#pickle.dump(T,open('T.p','wb'))
T = pickle.load(open('T.p','rb'))

In [35]:
T

RFE(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                 fit_intercept=True, intercept_scaling=1,
                                 l1_ratio=None, max_iter=100,
                                 multi_class='auto', n_jobs=None, penalty='l2',
                                 random_state=None, solver='lbfgs', tol=0.0001,
                                 verbose=0, warm_start=False),
    n_features_to_select=200, step=1, verbose=0)

In [36]:
mask = T.get_support()
mask

array([False, False, False,  True,  True, False, False, False, False,
        True,  True, False,  True, False, False,  True, False, False,
       False, False, False, False,  True, False, False,  True, False,
       False, False, False,  True, False, False,  True, False, False,
        True, False, False, False, False, False, False,  True,  True,
        True, False, False, False,  True, False,  True, False, False,
       False, False,  True,  True, False, False,  True,  True, False,
       False, False,  True, False, False,  True, False,  True, False,
       False,  True,  True, False,  True, False,  True,  True, False,
        True, False,  True, False,  True,  True, False, False, False,
       False, False,  True,  True, False,  True, False, False, False,
        True, False,  True,  True, False, False,  True,  True, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False,  True,

In [39]:
np.arange(500)[mask]

array([  3,   4,   9,  10,  12,  15,  22,  25,  30,  33,  36,  43,  44,
        45,  49,  51,  56,  57,  60,  61,  65,  68,  70,  73,  74,  76,
        78,  79,  81,  83,  85,  86,  92,  93,  95,  99, 101, 102, 105,
       106, 108, 115, 122, 127, 128, 129, 130, 131, 134, 135, 139, 140,
       141, 142, 143, 148, 150, 151, 153, 154, 156, 157, 159, 163, 164,
       166, 167, 170, 174, 176, 178, 180, 183, 186, 187, 188, 189, 190,
       191, 194, 196, 205, 206, 207, 210, 211, 213, 219, 220, 223, 224,
       226, 229, 231, 232, 233, 234, 235, 236, 239, 241, 245, 246, 248,
       250, 254, 256, 259, 260, 263, 267, 268, 269, 270, 272, 274, 275,
       276, 278, 279, 282, 285, 290, 291, 295, 297, 300, 303, 304, 308,
       311, 314, 316, 317, 323, 325, 327, 331, 341, 344, 346, 349, 350,
       354, 355, 357, 359, 361, 363, 367, 372, 376, 378, 379, 386, 387,
       389, 390, 392, 398, 400, 401, 404, 411, 415, 417, 418, 423, 425,
       427, 430, 432, 437, 442, 443, 446, 447, 449, 450, 452, 45

# Embedded 

In [40]:
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import LinearSVC

In [42]:
M = LinearSVC(C=0.01,penalty='l1',dual=False).fit(X,y)

In [43]:
T = SelectFromModel(M,prefit=True)

In [44]:
T

SelectFromModel(estimator=LinearSVC(C=0.01, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    loss='squared_hinge', max_iter=1000,
                                    multi_class='ovr', penalty='l1',
                                    random_state=None, tol=0.0001, verbose=0),
                max_features=None, norm_order=1, prefit=True, threshold=None)

In [45]:
X_new2 = T.transform(X)

In [46]:
X_new2.shape

(6004, 257)

# Corr Filter

In [49]:
c = np.array([])
for i in range(X.shape[1]):
    fi = X[:,i]
    ci = fi.dot(y)/((fi.dot(fi)*y.dot(y))**0.5)
    c = np.hstack((c,ci))

In [55]:
c_abs = np.abs(c)

In [58]:
idx = np.argsort(c_abs)[::-1][:10]

In [59]:
FNames = np.asarray(df.columns)

In [60]:
FNames[idx]

array(['yA115', 'yA102', 'yA41', 'yA59', 'yA179', 'yA155', 'yA94', 'yA6',
       'yA197', 'yA47'], dtype=object)

In [62]:
D = X.T.dot(y)

In [63]:
len(D)

2401