In [1]:
import numpy as np
from numpy import linalg as LA

In [3]:
A = np.random.rand(3,3)
print(A)

[[0.62430146 0.56217933 0.76794541]
 [0.05868136 0.99882148 0.066251  ]
 [0.42926049 0.2958087  0.80455664]]


In [4]:
type(A)

numpy.ndarray

In [5]:
A.shape

(3, 3)

In [6]:
LA.det(A)

0.16297522978169404

In [7]:
invA = LA.inv(A)

In [8]:
print(invA)

[[ 4.8106134  -1.38143801 -4.47795305]
 [-0.11519261  1.05928527  0.02272423]
 [-2.52428627  0.34758393  3.62371789]]


In [9]:
A.dot(invA)

array([[ 1.00000000e+00,  3.55001404e-17,  1.29674771e-16],
       [-3.32762213e-17,  1.00000000e+00,  2.31539155e-17],
       [ 3.56675647e-16,  2.24711136e-17,  1.00000000e+00]])

In [10]:
A

array([[0.62430146, 0.56217933, 0.76794541],
       [0.05868136, 0.99882148, 0.066251  ],
       [0.42926049, 0.2958087 , 0.80455664]])

In [11]:
LA.svd?

In [12]:
U,D,VT = LA.svd(A)

In [13]:
U.dot(U.T)

array([[1.00000000e+00, 2.01614298e-16, 4.64602660e-16],
       [2.01614298e-16, 1.00000000e+00, 2.27724578e-16],
       [4.64602660e-16, 2.27724578e-16, 1.00000000e+00]])

In [15]:
VT.dot(VT.T)

array([[ 1.00000000e+00,  5.91147659e-17, -1.43272968e-17],
       [ 5.91147659e-17,  1.00000000e+00, -9.58729150e-17],
       [-1.43272968e-17, -9.58729150e-17,  1.00000000e+00]])

In [16]:
D

array([1.5917992 , 0.81892519, 0.12502276])

In [17]:
D.shape

(3,)

In [18]:
A = np.array([[1,0,0],[0,1,0],[0,0,0]])

In [19]:
A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [20]:
b = np.array([0,0,1])

In [22]:
LA.lstsq(A,b)

C:\Users\DeLL\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([0., 0., 0.]), array([], dtype=float64), 2, array([1., 1., 0.]))

In [23]:
LA.det(A)

0.0

In [24]:
LA.inv(A)

LinAlgError: Singular matrix

In [25]:
LA.pinv(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [26]:
np.trace(A)

2

In [27]:
A = np.random.rand(3,3)

In [28]:
np.trace(A)

1.728055068605471

In [29]:
np.trace(A.dot(A.T))

3.530201949626745

In [30]:
LA.norm(A,'fro')**2

3.5302019496267443

In [31]:
np.trace(A.T.dot(A))

3.5302019496267447

In [32]:
a,b = LA.eig(A)

In [33]:
a

array([-0.38141643,  1.30794722,  0.80152428])

In [34]:
b

array([[-0.69682625,  0.83225951, -0.90505328],
       [ 0.7161843 ,  0.52001874, -0.31129776],
       [-0.03890021,  0.1921578 ,  0.28977969]])

In [35]:
B = A.T.dot(A)

In [37]:
a,b = LA.eig(B)

In [38]:
a

array([2.69888634, 0.0787162 , 0.75259941])

In [39]:
b

array([[-0.42247772, -0.8451672 , -0.32742172],
       [-0.46147983,  0.5114933 , -0.72485238],
       [-0.78009547,  0.15513546,  0.60612213]])

In [40]:
a,b = LA.eigh(B)

In [41]:
a

array([0.0787162 , 0.75259941, 2.69888634])

In [42]:
b

array([[ 0.8451672 ,  0.32742172,  0.42247772],
       [-0.5114933 ,  0.72485238,  0.46147983],
       [-0.15513546, -0.60612213,  0.78009547]])