In [3]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.18.1'

In [4]:
pd.__version__

'1.0.3'

In [5]:
a = np.array([1,2,3,5,-8])

In [6]:
a.dtype

dtype('int32')

In [7]:
b = np.array((2,3,5,6,7,8))

In [8]:
L = [1,2,3,4,5,'abc']

In [9]:
type(L)

list

In [10]:
type(a)

numpy.ndarray

In [11]:
print(a)

[ 1  2  3  5 -8]


In [12]:
A = np.array([[1,2,3,4],[3,5,-7,0]])

In [13]:
A.ndim

2

In [14]:
A = np.array([[[1,2,3,4],[3,4,5,8],[9,8,7,2]],[[5,-2,-3,-4],[-3,4,-5,8],[9,8,-7,2]]])

In [15]:
A.ndim

3

In [16]:
A.shape

(2, 3, 4)

In [17]:
A.shape[0]

2

In [18]:
A.shape[1]

3

In [19]:
A.shape[2]

4

In [20]:
A

array([[[ 1,  2,  3,  4],
        [ 3,  4,  5,  8],
        [ 9,  8,  7,  2]],

       [[ 5, -2, -3, -4],
        [-3,  4, -5,  8],
        [ 9,  8, -7,  2]]])

In [21]:
A[0,1,2]

5

In [22]:
A = np.arange(10)

In [23]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
A = np.arange(2,100,10)

In [25]:
A

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [26]:
np.random.permutation(np.arange(10))

array([9, 1, 7, 3, 5, 4, 8, 2, 0, 6])

In [27]:
np.arange(100).reshape(25,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [28]:
np.arange(100).reshape(25,5)

ValueError: cannot reshape array of size 100 into shape (25,5)

In [29]:
A = np.random.permutation(np.arange(10))

In [30]:
A

array([9, 0, 4, 1, 3, 7, 6, 5, 8, 2])

In [31]:
A[1:5]

array([0, 4, 1, 3])

In [32]:
A[1:7:2]

array([0, 1, 7])

In [33]:
A[::-1]

array([2, 8, 5, 6, 7, 3, 1, 4, 0, 9])

In [34]:
A = np.arange(20).reshape(5,4)

In [35]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
A[2,3]

11

In [37]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
A[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [40]:
A[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
A[::2,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [42]:
A = np.random.permutation(np.arange(10))

In [43]:
A

array([6, 0, 2, 1, 7, 4, 3, 8, 9, 5])

In [44]:
A[[1,5,2]]

array([0, 4, 2])

In [45]:
A<5

array([False,  True,  True,  True, False,  True,  True, False, False,
       False])

In [46]:
idx = A<5
A[idx]

array([0, 2, 1, 4, 3])

In [47]:
A[A<5]

array([0, 2, 1, 4, 3])

In [48]:
A[(A<5) & (A>2)]

array([4, 3])

In [49]:
A

array([6, 0, 2, 1, 7, 4, 3, 8, 9, 5])

In [50]:
B = A[1:5]

In [51]:
B

array([0, 2, 1, 7])

In [52]:
B[2] = -100

In [53]:
B

array([   0,    2, -100,    7])

In [54]:
A

array([   6,    0,    2, -100,    7,    4,    3,    8,    9,    5])

In [55]:
B = A[1:5].copy()

In [56]:
A

array([   6,    0,    2, -100,    7,    4,    3,    8,    9,    5])

In [57]:
B = A[A<5]

In [58]:
B

array([   0,    2, -100,    4,    3])

In [59]:
B[0] = 999

In [60]:
B

array([ 999,    2, -100,    4,    3])

In [61]:
A

array([   6,    0,    2, -100,    7,    4,    3,    8,    9,    5])

In [62]:
A = np.arange(20).reshape(5,4)

In [63]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [64]:
A+5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [65]:
A.shape

(5, 4)

In [66]:
B = np.arange(5).reshape(5,1)

In [67]:
B.shape

(5, 1)

In [68]:
A+B

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [69]:
import pandas as pd

In [70]:
pd.__version__

'1.0.3'

In [71]:
A = pd.Series([2,3,5,6],index=['a','b','c','d'])

In [72]:
type(A)

pandas.core.series.Series

In [73]:
A.values

array([2, 3, 5, 6], dtype=int64)

In [74]:
type(A.values)

numpy.ndarray

In [75]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [76]:
type(A.index)

pandas.core.indexes.base.Index

In [77]:
A['a']

2

In [78]:
A[0:2]

a    2
b    3
dtype: int64

In [79]:
A['a':'c']

a    2
b    3
c    5
dtype: int64

In [80]:
garades = pd.Series([4,3.5,3,2.5],index = ['A','A-','B','C'])
marks = pd.Series([85,75,65,55],index = ['A','A-','B','C'])
sheet = pd.DataFrame({'Gr':garades,'Mr':marks})

In [81]:
sheet

Gr  Mr
A   4.0  85
A-  3.5  75
B   3.0  65
C   2.5  55

In [82]:
sheet['Gr']

A     4.0
A-    3.5
B     3.0
C     2.5
Name: Gr, dtype: float64

In [83]:
sheet.columns

Index(['Gr', 'Mr'], dtype='object')

In [84]:
sheet.values

array([[ 4. , 85. ],
       [ 3.5, 75. ],
       [ 3. , 65. ],
       [ 2.5, 55. ]])

In [85]:
sheet.index

Index(['A', 'A-', 'B', 'C'], dtype='object')

In [86]:
sheet['NewC'] = np.random.randint(1,10,4)

In [87]:
sheet

Gr  Mr  NewC
A   4.0  85     9
A-  3.5  75     4
B   3.0  65     3
C   2.5  55     5

In [89]:
sheet.rename(columns={'NewC':'ColC'})

Gr  Mr  ColC
A   4.0  85     9
A-  3.5  75     4
B   3.0  65     3
C   2.5  55     5

In [90]:
sheet[sheet['Mr']>70]

Gr  Mr  NewC
A   4.0  85     9
A-  3.5  75     4

In [91]:
data = pd.Series(['a','b','c'],index=[1,3,5])

In [92]:
data[1]

'a'

In [93]:
data[1:3]

3    b
5    c
dtype: object

In [94]:
data.loc[1:3]

1    a
3    b
dtype: object

In [95]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [97]:
A = pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

In [98]:
A

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [99]:
A.dropna()

Empty DataFrame
Columns: [a, b, c]
Index: []

In [100]:
A = pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

In [101]:
A.fillna(0)

a  b    c
0  1.0  2  0.0
1  0.0  3  4.0

In [102]:
A = pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

In [103]:
A.isnull()

a      b      c
0  False  False   True
1   True  False  False

In [105]:
A['c'].isnull()

0     True
1    False
Name: c, dtype: bool

In [106]:
df = pd.DataFrame(np.random.randint(0,10,(3,4)),columns=list('ABCD'))

In [107]:
df

A  B  C  D
0  4  2  1  8
1  8  3  0  5
2  7  6  8  4

In [109]:
df2 = np.sin(df*np.pi/4)

In [110]:
type(df2)

pandas.core.frame.DataFrame

In [112]:
A = pd.DataFrame(np.random.randint(0,20,(2,2)),columns=list('AB'))
B = pd.DataFrame(np.random.randint(0,30,(3,3)),columns=list('BAC'))

In [113]:
A

A   B
0   2  19
1  12   8

In [114]:
B

B   A   C
0   6  12  24
1  12  26  15
2   2  27   5

In [115]:
A+B

A     B   C
0  14.0  25.0 NaN
1  38.0  20.0 NaN
2   NaN   NaN NaN

In [116]:
(A+B).fillna(0)

A     B    C
0  14.0  25.0  0.0
1  38.0  20.0  0.0
2   0.0   0.0  0.0

In [118]:
A.add(B,fill_value=0)

A     B     C
0  14.0  25.0  24.0
1  38.0  20.0  15.0
2  27.0   2.0   5.0

In [119]:
df = pd.DataFrame({'key':list('ABCABC'),'val':np.arange(6)},columns=['key','val'])

In [120]:
df

key  val
0   A    0
1   B    1
2   C    2
3   A    3
4   B    4
5   C    5

In [121]:
df.groupby('key').sum()

val
key     
A      3
B      5
C      7

In [125]:
df = pd.read_csv(r'C:\Users\DeLL\Desktop\ML\fullcourse\finalMaterial\Data\adult.data',header=None)

In [126]:
df.shape

(32561, 15)

In [127]:
df.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype='int64')

In [128]:
df.columns = ['C'+str(x) for x in range(df.shape[1])]

In [129]:
df.columns

Index(['C0', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10',
       'C11', 'C12', 'C13', 'C14'],
      dtype='object')

In [138]:
df.loc[:,['C0','C14']]

C0     C14
0      39   <=50K
1      50   <=50K
2      38   <=50K
3      53   <=50K
4      28   <=50K
...    ..     ...
32556  27   <=50K
32557  40    >50K
32558  58   <=50K
32559  22   <=50K
32560  52    >50K

[32561 rows x 2 columns]

In [139]:
df.head()

C0                 C1      C2          C3  C4                   C5  \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   C6              C7      C8       C9   C10  C11  C12  \
0        Adm-clerical   Not-in-family   White     Male  2174    0   40   
1     Exec-managerial         Husband   White     Male     0    0   13   
2   Handlers-cleaners   Not-in-family   White     Male     0    0   40   
3   Handlers-cleaners         Husband   Black     Male     0    0   40   
4      Prof-specialty            Wife   Black   Female     0    0   40   

              C13     C14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

In [140]:
df.tail()

C0             C1      C2           C3  C4                   C5  \
32556  27        Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40        Private  154374      HS-grad   9   Married-civ-spouse   
32558  58        Private  151910      HS-grad   9              Widowed   
32559  22        Private  201490      HS-grad   9        Never-married   
32560  52   Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                       C6          C7      C8       C9    C10  C11  C12  \
32556        Tech-support        Wife   White   Female      0    0   38   
32557   Machine-op-inspct     Husband   White     Male      0    0   40   
32558        Adm-clerical   Unmarried   White   Female      0    0   40   
32559        Adm-clerical   Own-child   White     Male      0    0   20   
32560     Exec-managerial        Wife   White   Female  15024    0   40   

                  C13     C14  
32556   United-States   <=50K  
32557   United-States    >50K  
32558   United-States   <=50K  
32559   United-States   <=50K  
32560   United-States    >50K

In [142]:
L = df['C14'].unique()

In [143]:
L[0]

' <=50K'

In [144]:
L[1]

' >50K'

In [145]:
idx = df['C14']==L[0]

In [147]:
df['C14'].loc[idx] = -1

C:\Users\DeLL\anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [148]:
df['C14'].loc[~idx] = 1

In [149]:
df['C14']

0        -1
1        -1
2        -1
3        -1
4        -1
         ..
32556    -1
32557     1
32558    -1
32559    -1
32560     1
Name: C14, Length: 32561, dtype: object

In [150]:
df['C14'].unique()

array([-1, 1], dtype=object)

In [151]:
df.head()

C0                 C1      C2          C3  C4                   C5  \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   C6              C7      C8       C9   C10  C11  C12  \
0        Adm-clerical   Not-in-family   White     Male  2174    0   40   
1     Exec-managerial         Husband   White     Male     0    0   13   
2   Handlers-cleaners   Not-in-family   White     Male     0    0   40   
3   Handlers-cleaners         Husband   Black     Male     0    0   40   
4      Prof-specialty            Wife   Black   Female     0    0   40   

              C13 C14  
0   United-States  -1  
1   United-States  -1  
2   United-States  -1  
3   United-States  -1  
4            Cuba  -1

In [152]:
df['C1'].unique().size

9

In [153]:
df = pd.get_dummies(df,columns=['C1'])

In [154]:
df.shape

(32561, 23)

In [155]:
df.columns

Index(['C0', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11',
       'C12', 'C13', 'C14', 'C1_ ?', 'C1_ Federal-gov', 'C1_ Local-gov',
       'C1_ Never-worked', 'C1_ Private', 'C1_ Self-emp-inc',
       'C1_ Self-emp-not-inc', 'C1_ State-gov', 'C1_ Without-pay'],
      dtype='object')

In [156]:
15-1+9

23

In [157]:
df = pd.read_csv(r'C:\Users\DeLL\Desktop\ML\fullcourse\finalMaterial\Data\adult.data',header=None)

In [158]:
df.columns = ['C'+str(x) for x in range(df.shape[1])]

In [160]:
df['C1'].isnull().sum()

0

In [161]:
df['C1'].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [163]:
df2 = pd.get_dummies(df,columns=['C1','C14'])

In [164]:
df2.columns

Index(['C0', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11',
       'C12', 'C13', 'C1_ ?', 'C1_ Federal-gov', 'C1_ Local-gov',
       'C1_ Never-worked', 'C1_ Private', 'C1_ Self-emp-inc',
       'C1_ Self-emp-not-inc', 'C1_ State-gov', 'C1_ Without-pay',
       'C14_ <=50K', 'C14_ >50K'],
      dtype='object')

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   C0      32561 non-null  int64 
 1   C1      32561 non-null  object
 2   C2      32561 non-null  int64 
 3   C3      32561 non-null  object
 4   C4      32561 non-null  int64 
 5   C5      32561 non-null  object
 6   C6      32561 non-null  object
 7   C7      32561 non-null  object
 8   C8      32561 non-null  object
 9   C9      32561 non-null  object
 10  C10     32561 non-null  int64 
 11  C11     32561 non-null  int64 
 12  C12     32561 non-null  int64 
 13  C13     32561 non-null  object
 14  C14     32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [167]:
df2.head()

C0      C2          C3  C4                   C5                  C6  \
0  39   77516   Bachelors  13        Never-married        Adm-clerical   
1  50   83311   Bachelors  13   Married-civ-spouse     Exec-managerial   
2  38  215646     HS-grad   9             Divorced   Handlers-cleaners   
3  53  234721        11th   7   Married-civ-spouse   Handlers-cleaners   
4  28  338409   Bachelors  13   Married-civ-spouse      Prof-specialty   

               C7      C8       C9   C10  ...  C1_ Federal-gov  C1_ Local-gov  \
0   Not-in-family   White     Male  2174  ...                0              0   
1         Husband   White     Male     0  ...                0              0   
2   Not-in-family   White     Male     0  ...                0              0   
3         Husband   Black     Male     0  ...                0              0   
4            Wife   Black   Female     0  ...                0              0   

  C1_ Never-worked  C1_ Private  C1_ Self-emp-inc  C1_ Self-emp-not-inc  \
0                0            0                 0                     0   
1                0            0                 0                     1   
2                0            1                 0                     0   
3                0            1                 0                     0   
4                0            1                 0                     0   

   C1_ State-gov  C1_ Without-pay  C14_ <=50K  C14_ >50K  
0              1                0           1          0  
1              0                0           1          0  
2              0                0           1          0  
3              0                0           1          0  
4              0                0           1          0  

[5 rows x 24 columns]

In [168]:
df2.to_csv(r"C:\Users\DeLL\Desktop\ML\fullcourse\finalMaterial\Data\abc.csv")